name: Build Ubuntu

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.0
        pip install torch six tensorboard
        pip install -r painter/requirements.txt

    - name: Build software
      run: pyinstaller --noconfirm --clean main.spec

    - name: Make installer
      run: |
        cd painter/
        mkdir -p ubuntu_setup/usr/local/bin
        cp -r ../dist/RootPainter3D ubuntu_setup/usr/local/bin
        dpkg-deb --build --root-owner-group ubuntu_setup
        cp -r ubuntu_setup.deb ../dist/RootPainter3D-0.0.1-ubuntu.deb

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{github.workspace}}/dist/RootPainter3D-*
        if-no-files-found: error
