name: Build macOS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.0
        pip install torch six tensorboard
        pip install -r painter/requirements.txt

    - name: Build software
      run: pyinstaller --noconfirm --clean main.spec

    - name: Make installer
      run: |
        git clone https://github.com/andreped/quickpkg.git
        quickpkg/quickpkg dist/RootPainter3D.app --output RootPainter3D-0.0.1-macOS.pkg
        cp -r RootPainter3D-0.0.1-macOS.pkg dist/RootPainter3D-0.0.1-macOS.pkg

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{github.workspace}}/dist/RootPainter3D-*
        if-no-files-found: error
