# Copyright (C) 2022 André Pedersen

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Build macOS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python '3.9.5'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.5'

    - name: Install dependencies
      run: |
        cd painter
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install pyinstaller==5.3
        pip install -r requirements.txt
        brew install create-dmg

    - name: Build software
      run: |
        cd painter
        source env/bin/activate
        python build/freeze.py
        python install_fixes.py

    - name: Make installer
      run: |
        cd painter
        source env/bin/activate
        python build/installer.py
        cp -r dist/RootPainter3D.dmg dist/RootPainter3D-0.0.1-macOS.dmg

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{github.workspace}}/painter/dist/RootPainter3D-*
        if-no-files-found: error
